function extractEducationAlabama(cell) {
    // Check if the input cell is empty
    if (!cell) return '';
  
    const alabamaUniversities = [
        "Air University", "Alabama A&M University", "Alabama College of Osteopathic Medicine", "Alabama State University",
        "Amridge University", "Athens State University", "Auburn University", "Auburn University at Montgomery",
        "Bevill State Community College", "Birmingham School of Law", "Bishop State Community College", "Calhoun Community College",
        "Central Alabama Community College", "Chattahoochee Valley Community College", "Coastal Alabama Community College",
        "Columbia Southern University", "Community College of the Air Force", "Enterprise State Community College", "Faulkner University",
        "Gadsden State Community College", "H. Councill Trenholm State Community College", "Heritage Christian University", "Highlands College",
        "Huntingdon College", "Huntsville Bible College", "J.F. Drake State Community and Technical College", "J. F. Ingram State Technical College",
        "Jacksonville State University", "Jefferson State Community College", "Lawson State Community College", "Lurleen B. Wallace Community College",
        "Marion Military Institute", "Miles College", "Miles Law School", "Northeast Alabama Community College", "Northwest–Shoals Community College",
        "Oakwood University", "Reid State Technical College", "Samford University", "Selma University", "Shelton State Community College",
        "Snead State Community College", "Southern Union State Community College", "Spring Hill College", "Stillman College", "Talladega College",
        "Troy University", "Tuskegee University", "United States Sports Academy", "University of Alabama", "University of Alabama at Birmingham",
        "University of Alabama in Huntsville", "University of Mobile", "University of Montevallo", "University of North Alabama", "University of South Alabama",
        "University of West Alabama", "Wallace Community College", "Wallace Community College Selma", "Wallace State Community College Columbia College Missouri",
        "Edward Via College of Osteopathic Medicine", "Embry-Riddle Aeronautical University", "Florida Institute of Technology", "Southeastern University",
        "United States Army Command and General Staff College", "Alabama Presbyterian College", "Birmingham–Southern College", "Concordia College Alabama",
        "Daniel Payne College", "Judson College", "Southeastern Bible College", "Southern Benedictine College", "Virginia College"
    ];
    const oldNamesToNew = {
        "Alabama Polytechnic University": "Auburn University",
        "Alabama Polytechnic Institute": "Auburn University",
        "Alabama State Teachers College": "University of North Alabama",
        "Athens State Teachers College": "Athens State University",
        "Florence State Teachers College": "University of North Alabama",
        "Florence State College": "University of North Alabama",
        "Florence State University": "University of North Alabama",
        "Jacksonville State Teachers College": "Jacksonville State University",
        "Livingston State Teachers College": "University of West Alabama",
        "Livingston State College": "University of West Alabama",
        "Livingston State University": "University of West Alabama",
        "Montevallo State College": "University of Montevallo",
        "Montevallo State University": "University of Montevallo",
        "Troy State College": "Troy University",
        "Troy State University": "Troy University"
    };

    const citiesAndTowns = [
        "Abbeville",
        "Adamsville",
        "Addison",
        "Akron",
        "Alabaster",
        "Albertville",
        "Alexander City",
        "Aliceville",
        "Allgood",
        "Altoona",
        "Andalusia",
        "Anderson",
        "Anniston",
        "Arab",
        "Ardmore",
        "Argo",
        "Ariton",
        "Arley",
        "Ashford",
        "Ashland",
        "Ashville",
        "Athens",
        "Atmore",
        "Attalla",
        "Auburn",
        "Autaugaville",
        "Avon",
        "Babbie",
        "Baileyton",
        "Bakerhill",
        "Banks",
        "Bay Minette",
        "Bayou La Batre",
        "Bear Creek",
        "Beatrice",
        "Beaverton",
        "Belk",
        "Benton",
        "Berlin",
        "Berry",
        "Bessemer",
        "Billingsley",
        "Birmingham",
        "Black",
        "Blountsville",
        "Blue Springs",
        "Boaz",
        "Boligee",
        "Bon Air",
        "Brantley",
        "Brent",
        "Brewton",
        "Bridgeport",
        "Brighton",
        "Brilliant",
        "Brookside",
        "Brookwood",
        "Brundidge",
        "Butler",
        "Calera",
        "Camden",
        "Camp Hill",
        "Carbon Hill",
        "Cardiff",
        "Carolina",
        "Carrollton",
        "Castleberry",
        "Cedar Bluff",
        "Center Point",
        "Centre",
        "Centreville",
        "Chatom",
        "Chelsea",
        "Cherokee",
        "Chickasaw",
        "Childersburg",
        "Citronelle",
        "Clanton",
        "Clay",
        "Clayhatchee",
        "Clayton",
        "Cleveland",
        "Clio",
        "Coaling",
        "Coffee Springs",
        "Coffeeville",
        "Coker",
        "Collinsville",
        "Colony",
        "Columbia",
        "Columbiana",
        "Coosada",
        "Cordova",
        "Cottonwood",
        "County Line",
        "Courtland",
        "Cowarts",
        "Creola",
        "Crossville",
        "Cuba",
        "Cullman",
        "Cusseta",
        "Dadeville",
        "Daleville",
        "Daphne",
        "Dauphin Island",
        "Daviston",
        "Dayton",
        "Deatsville",
        "Decatur",
        "Demopolis",
        "Detroit",
        "Dodge City",
        "Dora",
        "Dothan",
        "Double Springs",
        "Douglas",
        "Dozier",
        "Dutton",
        "East Brewton",
        "Eclectic",
        "Edwardsville",
        "Elba",
        "Elberta",
        "Eldridge",
        "Elkmont",
        "Elmore",
        "Emelle",
        "Enterprise",
        "Epes",
        "Ethelsville",
        "Eufaula",
        "Eutaw",
        "Eva",
        "Evergreen",
        "Excel",
        "Fairfield",
        "Fairhope",
        "Fairview",
        "Falkville",
        "Faunsdale",
        "Fayette",
        "Five Points",
        "Flomaton",
        "Florala",
        "Florence",
        "Foley",
        "Forkland",
        "Fort Deposit",
        "Fort Payne",
        "Franklin",
        "Frisco City",
        "Fruithurst",
        "Fulton",
        "Fultondale",
        "Fyffe",
        "Gadsden",
        "Gainesville",
        "Gantt",
        "Garden City",
        "Gardendale",
        "Gaylesville",
        "Geiger",
        "Geneva",
        "Georgiana",
        "Geraldine",
        "Gilbertown",
        "Glen Allen",
        "Glencoe",
        "Glenwood",
        "Goldville",
        "Good Hope",
        "Goodwater",
        "Gordo",
        "Gordon",
        "Gordonville",
        "Goshen",
        "Grant",
        "Graysville",
        "Greensboro",
        "Greenville",
        "Grimes",
        "Grove Hill",
        "Guin",
        "Gulf Shores",
        "Guntersville",
        "Gurley",
        "Gu-Win",
        "Hackleburg",
        "Haleburg",
        "Haleyville",
        "Hamilton",
        "Hammondville",
        "Hanceville",
        "Harpersville",
        "Hartford",
        "Hartselle",
        "Hayden",
        "Hayneville",
        "Headland",
        "Heath",
        "Heflin",
        "Helena",
        "Henagar",
        "Highland Lake",
        "Hillsboro",
        "Hobson City",
        "Hodges",
        "Hokes Bluff",
        "Holly Pond",
        "Hollywood",
        "Homewood",
        "Hoover",
        "Horn Hill",
        "Hueytown",
        "Huntsville",
        "Hurtsboro",
        "Hytop",
        "Ider",
        "Indian Springs Village",
        "Irondale",
        "Jackson",
        "Jackson's Gap",
        "Jacksonville",
        "Jasper",
        "Jemison",
        "Kansas",
        "Kellyton",
        "Kennedy",
        "Killen",
        "Kimberly",
        "Kinsey",
        "Kinston",
        "LaFayette",
        "Lake View",
        "Lakeview",
        "Lanett",
        "Langston",
        "Leeds",
        "Leesburg",
        "Leighton",
        "Lester",
        "Level Plains",
        "Lexington",
        "Libertyville",
        "Lincoln",
        "Linden",
        "Lineville",
        "Lisman",
        "Littleville",
        "Livingston",
        "Loachapoka",
        "Lockhart",
        "Locust Fork",
        "Louisville",
        "Lowndesboro",
        "Loxley",
        "Luverne",
        "Lynn",
        "Madison",
        "Madrid",
        "Magnolia Springs",
        "Malvern",
        "Maplesville",
        "Margaret",
        "Marion",
        "Maytown",
        "McIntosh",
        "McKenzie",
        "McMullen",
        "Memphis",
        "Mentone",
        "Midfield",
        "Midland City",
        "Midway",
        "Millbrook",
        "Millport",
        "Millry",
        "Mobile",
        "Monroeville",
        "Montevallo",
        "Montgomery",
        "Moody",
        "Mooresville",
        "Morris",
        "Mosses",
        "Moundville",
        "Mountain Brook",
        "Mulga",
        "Munford",
        "Muscle Shoals",
        "Myrtlewood",
        "Napier Field",
        "Natural Bridge",
        "Nauvoo",
        "Nectar",
        "Needham",
        "New Brockton",
        "New Hope",
        "New Site",
        "Newbern",
        "Newton",
        "Newville",
        "North Courtland",
        "North Johns",
        "Northport",
        "Notasulga",
        "Oak Grove",
        "Oak Hill",
        "Oakman",
        "Odenville",
        "Ohatchee",
        "Oneonta",
        "Onycha",
        "Opelika",
        "Opp",
        "Orange Beach",
        "Orrville",
        "Owens Cross Roads",
        "Oxford",
        "Ozark",
        "Paint Rock",
        "Parrish",
        "Pelham",
        "Pell City",
        "Pennington",
        "Perdido Beach",
        "Petrey",
        "Phenix City",
        "Phil Campbell",
        "Pickensville",
        "Piedmont",
        "Pike Road",
        "Pinckard",
        "Pine Apple",
        "Pine Hill",
        "Pine Level",
        "Pine Ridge",
        "Pinson",
        "Pisgah",
        "Pleasant Grove",
        "Pleasant Groves",
        "Pollard",
        "Powell",
        "Prattville",
        "Priceville",
        "Prichard",
        "Providence",
        "Ragland",
        "Rainbow City",
        "Rainsville",
        "Ranburne",
        "Red Bay",
        "Red Level",
        "Reece City",
        "Reform",
        "Rehobeth",
        "Repton",
        "Ridgeville",
        "River Falls",
        "Riverside",
        "Riverview",
        "Roanoke",
        "Robertsdale",
        "Rockford",
        "Rogersville",
        "Rosa",
        "Russellville",
        "Rutledge",
        "St. Florian",
        "Samson",
        "Sand Rock",
        "Sanford",
        "Saraland",
        "Sardis City",
        "Satsuma",
        "Scottsboro",
        "Section",
        "Selma",
        "Sheffield",
        "Shiloh",
        "Shorter",
        "Silas",
        "Silverhill",
        "Sipsey",
        "Skyline",
        "Slocomb",
        "Smiths Station",
        "Snead",
        "Somerville",
        "South Vinemont",
        "Southside",
        "Spanish Fort",
        "Springville",
        "Steele",
        "Stevenson",
        "Sulligent",
        "Sumiton",
        "Summerdale",
        "Susan Moore",
        "Sweet Water",
        "Sylacauga",
        "Sylvan Springs",
        "Sylvania",
        "Talladega Springs",
        "Talladega",
        "Tallassee",
        "Tarrant",
        "Taylor",
        "Thomaston",
        "Thomasville",
        "Thorsby",
        "Town Creek",
        "Toxey",
        "Trafford",
        "Triana",
        "Trinity",
        "Troy",
        "Trussville",
        "Tuscaloosa",
        "Tuscumbia",
        "Tuskegee",
        "Twin",
        "Union Grove",
        "Union Springs",
        "Union",
        "Uniontown",
        "Valley",
        "Valley Grande",
        "Valley Head",
        "Vance",
        "Vernon",
        "Vestavia Hills",
        "Vina",
        "Vincent",
        "Vredenburgh",
        "Wadley",
        "Waldo",
        "Walnut Grove",
        "Warrior",
        "Waterloo",
        "Waverly",
        "Weaver",
        "Webb",
        "Wedowee",
        "West Blocton",
        "West Jefferson",
        "West Point",
        "Westover",
        "Wetumpka",
        "White Hall",
        "Wilsonville",
        "Wilton",
        "Winfield",
        "Woodland",
        "Woodstock",
        "Woodville",
        "Yellow Bluff",
        "York"
    ]
  
    // Check for any institutions in the list that match the input cell
    const foundInstitutions = alabamaUniversities.filter(inst => {
        const oldName = oldNamesToNew[inst];
        return cell.includes(inst) || (oldName && cell.includes(oldName));
    });
  
    // Check if there's any Alabama University
    const hasAlabamaUniversity = foundInstitutions.some(inst => alabamaUniversities.includes(inst));
  
    // Check if there's any Alabama cities
    const hasAlabamaCity = citiesAndTowns.some(city => cell.includes(city));
  
    // Return the found institutions or a message if none found
    if (hasAlabamaUniversity) {
        return foundInstitutions.join(', ');
    } else if (hasAlabamaCity) {
        const foundCities = citiesAndTowns.filter(city => cell.includes(city));
        return foundCities.join(', ');
    } else {
        return 'No Alabama institutions or cities found';
    }
  }

